apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-gateway
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-gateway
  template:
    metadata:
      labels:
        app: grpc-gateway
    spec:
      containers:
        - name: grpc-gateway
          image: markuysa/grpc-gateway:latest
          ports:
            - containerPort: 8000
          env:
            - name: CONFIG_PATH
              value: "/internal/config/config.yaml"
          volumeMounts:
            - mountPath: /internal/config
              name: config-data
          readinessProbe:
            httpGet:
              path: /ready
              port: 5050
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /live
              port: 5050
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: config-data
          configMap:
            defaultMode: 420
            name: grpc-gateway-configmap
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: grpc-gateway
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grpc-gateway
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-gateway
  namespace: production
spec:
  selector:
    app: grpc-gateway
  ports:
    - name: http-health
      protocol: TCP
      port: 5050
      targetPort: 5050

    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000

    - name: metrics
      protocol: TCP
      targetPort: 9000
      port: 9000
  type: ClusterIP
